const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOG_OUT = 'LOGOUT';
const LOAD_PROFILE = 'LOAD_PROFILE';

// Home
const HOME_VIDEO_SUCCESS = 'HOME_VIDEO_SUCCESS';
const HOME_VIDEO_REQUEST = 'HOME_VIDEO_REQUEST';
const HOME_VIDEO_FAILED = 'HOME_VIDEO_FAILED';

export {
	LOGIN_SUCCESS,
	LOGIN_FAILED,
	LOGIN_REQUEST,
	LOG_OUT,
	LOAD_PROFILE,
	HOME_VIDEO_SUCCESS,
	HOME_VIDEO_REQUEST,
	HOME_VIDEO_FAILED,
};
