const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOG_OUT = 'LOGOUT';
const LOAD_PROFILE = 'LOAD_PROFILE';

// Home
const HOME_VIDEO_SUCCESS = 'HOME_VIDEO_SUCCESS';
const HOME_VIDEO_REQUEST = 'HOME_VIDEO_REQUEST';
const HOME_VIDEO_FAILED = 'HOME_VIDEO_FAILED';

// Video
const SELECT_VIDEO_REQUEST = 'SELECT_VIDEO_REQUEST';
const SELECT_VIDEO_SUCCESS = 'SELECT_VIDEO_SUCCESS';
const SELECT_VIDEO_FAILED = 'SELECT_VIDEO_FAILED';

// Channel
const CHANNEL_DETAIL_REQUEST = 'CHANNEL_DETAIL_REQUEST';
const CHANNEL_DETAIL_SUCCESS = 'CHANNEL_DETAIL_SUCCESS';
const CHANNEL_DETAIL_FAILED = 'CHANNEL_DETAIL_FAILED';

// Subscription
const SET_SUBSCRIPTION_STATUS = 'SET_SUBSCRIPTION_STATUS';

// Comment
const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';
const COMMENT_LIST_FAILED = 'COMMENT_LIST_FAILED ';
const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS ';
const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED ';
// Related Video
const RELATED_VIDEO_REQUEST = 'RELATED_VIDEO_REQUEST';
const RELATED_VIDEO_SUCCESS = 'RELATED_VIDEO_SUCCESS';
const RELATED_VIDEO_FAILED = 'RELATED_VIDEO_FAILED';
// Search Video
const SEARCH_VIDEO_REQUEST = 'SEARCH_VIDEO_REQUEST';
const SEARCH_VIDEO_SUCCESS = 'SEARCH_VIDEO_SUCCESS';
const SEARCH_VIDEO_FAILED = 'SEARCH_VIDEO_FAILED';
// Search Video
const SUBSCRIPTION_CHANNEL_REQUEST = 'SUBSCRIPTION_CHANNEL_REQUEST';
const SUBSCRIPTION_CHANNEL_SUCCESS = 'SUBSCRIPTION_CHANNEL_SUCCESS';
const SUBSCRIPTION_CHANNEL_FAILED = 'SUBSCRIPTION_CHANNEL_FAILED';
// Channel Video
const VIDEO_CHANNEL_REQUEST = 'VIDEO_CHANNEL_REQUEST';
const VIDEO_CHANNEL_SUCCESS = 'VIDEO_CHANNEL_SUCCESS';
const VIDEO_CHANNEL_FAILED = 'VIDEO_CHANNEL_FAILED';
export {
	LOGIN_SUCCESS,
	LOGIN_FAILED,
	LOGIN_REQUEST,
	LOG_OUT,
	LOAD_PROFILE,
	//
	HOME_VIDEO_SUCCESS,
	HOME_VIDEO_REQUEST,
	HOME_VIDEO_FAILED,
	//
	SELECT_VIDEO_REQUEST,
	SELECT_VIDEO_SUCCESS,
	SELECT_VIDEO_FAILED,
	//
	CHANNEL_DETAIL_REQUEST,
	CHANNEL_DETAIL_SUCCESS,
	CHANNEL_DETAIL_FAILED,
	//
	SET_SUBSCRIPTION_STATUS,
	//
	COMMENT_LIST_SUCCESS,
	COMMENT_LIST_REQUEST,
	COMMENT_LIST_FAILED,
	//
	ADD_COMMENT_SUCCESS,
	ADD_COMMENT_FAILED,
	//
	RELATED_VIDEO_REQUEST,
	RELATED_VIDEO_SUCCESS,
	RELATED_VIDEO_FAILED,
	//
	SEARCH_VIDEO_REQUEST,
	SEARCH_VIDEO_SUCCESS,
	SEARCH_VIDEO_FAILED,
	//
	SUBSCRIPTION_CHANNEL_REQUEST,
	SUBSCRIPTION_CHANNEL_SUCCESS,
	SUBSCRIPTION_CHANNEL_FAILED,
	//
	VIDEO_CHANNEL_REQUEST,
	VIDEO_CHANNEL_SUCCESS,
	VIDEO_CHANNEL_FAILED,
};
