const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOG_OUT = 'LOGOUT';
const LOAD_PROFILE = 'LOAD_PROFILE';

// Home
const HOME_VIDEO_SUCCESS = 'HOME_VIDEO_SUCCESS';
const HOME_VIDEO_REQUEST = 'HOME_VIDEO_REQUEST';
const HOME_VIDEO_FAILED = 'HOME_VIDEO_FAILED';

// Video
const SELECT_VIDEO_REQUEST = 'SELECT_VIDEO_REQUEST';
const SELECT_VIDEO_SUCCESS = 'SELECT_VIDEO_SUCCESS';
const SELECT_VIDEO_FAILED = 'SELECT_VIDEO_FAILED';

// Channel
const CHANNEL_DETAIL_REQUEST = 'CHANNEL_DETAIL_REQUEST';
const CHANNEL_DETAIL_SUCCESS = 'CHANNEL_DETAIL_SUCCESS';
const CHANNEL_DETAIL_FAILED = 'CHANNEL_DETAIL_FAILED';

// Subscription
const SET_SUBSCRIPTION_STATUS = 'SET_SUBSCRIPTION_STATUS';

export {
	LOGIN_SUCCESS,
	LOGIN_FAILED,
	LOGIN_REQUEST,
	LOG_OUT,
	LOAD_PROFILE,
	//
	HOME_VIDEO_SUCCESS,
	HOME_VIDEO_REQUEST,
	HOME_VIDEO_FAILED,
	//
	SELECT_VIDEO_REQUEST,
	SELECT_VIDEO_SUCCESS,
	SELECT_VIDEO_FAILED,
	//
	CHANNEL_DETAIL_REQUEST,
	CHANNEL_DETAIL_SUCCESS,
	CHANNEL_DETAIL_FAILED,
	//
	SET_SUBSCRIPTION_STATUS,
};
